1. SELECT TOP 10 * FROM PRODUCTS
   ORDER BY PRICE DESC;

2. SELECT DISTINCT CATEGORY
   FROM PRODUCTS;

3. SELECT * FROM PRODUCTS
   WHERE PRICE > 100;

4. SELECT * FROM CUSTOMERS 
   WHERE FIRSTNAME LIKE 'A%';

5. SELECT * FROM PRODUCTS
   ORDER BY PRICE ASC;

6. SELECT * FROM EMPLOYEES
   WHERE SALARY >= 60000 AND DEPARTMENTNAME = 'HR';

7. SELECT 
      FIRSTNAME,
      LASTNAME,
	    ISNULL (EMAIL, 'noemail@example.com')
   FROM EMPLOYEES;

8. SELECT * FROM PRODUCTS
   WHERE PRICE BETWEEN 50 AND 100;

9. SELECT DISTINCT CATEGORY, PRODUCTNAME FROM PRODUCTS;

10.SELECT DISTINCT CATEGORY, PRODUCTNAME 
   FROM PRODUCTS
   ORDER BY PRODUCTNAME DESC;

11.SELECT TOP 10 * FROM PRODUCTS
   ORDER BY PRICE DESC;

12.SELECT EMPLOYEEID,
	   COALESCE(FIRSTNAME, LASTNAME) AS PREFERRED_NAME
	   FROM EMPLOYEES;

13.SELECT DISTINCT CATEGORY, PRICE FROM PRODUCTS;

14.SELECT * FROM EMPLOYEES 
   WHERE (AGE BETWEEN 30 AND 40) OR (DEPARTMENTNAME = 'MARKETING');

15.SELECT * FROM EMPLOYEES
   ORDER BY SALARY DESC
   OFFSET 10 ROWS 
   FETCH NEXT 10 ROWS ONLY;

16.SELECT * FROM PRODUCTS 
   WHERE PRICE <= 1000 AND STOCKQUANTITY > 50
   ORDER BY STOCKQUANTITY ASC;

17.SELECT * FROM PRODUCTS
   WHERE PRODUCTNAME LIKE '%E%';

18.SELECT * FROM EMPLOYEES
   WHERE DEPARTMENTNAME IN('HR', 'IT', 'FINANCE');

19.SELECT * FROM CUSTOMERS
   ORDER BY CITY ASC, POSTALCODE DESC;

20.SELECT TOP 5 * FROM SALES
   ORDER BY SALEAMOUNT DESC;


21.SELECT EMPLOYEEID,
          CONCAT(FIRSTNAME, ' ', LASTNAME) AS FULLNAME
   FROM EMPLOYEES;

22.SELECT DISTINCT CATEGORY, PRODUCTNAME, PRICE 
   FROM PRODUCTS
   WHERE PRICE > 50;

23.SELECT * FROM PRODUCTS
   WHERE PRICE < (SELECT AVG(PRICE) * 0.10 FROM PRODUCTS);

24.SELECT * FROM EMPLOYEES
   WHERE AGE < 30 AND DEPARTMENTNAME IN('HR', 'IT');

25.SELECT * FROM CUSTOMERS
   WHERE EMAIL LIKE '%@gmail.com';

26.SELECT * FROM EMPLOYEES
   WHERE SALARY > ALL(SELECT SALARY 
                      FROM EMPLOYEES 
				              WHERE DEPARTMENTNAME = 'SALES');

27.SELECT *
   FROM Orders
   WHERE OrderDate BETWEEN DATEADD(DAY, -180, GETDATE()) AND GETDATE();



