1. SELECT * FROM PRODUCTS
   SELECT PRODUCTID, PRODUCTNAME AS NAME FROM PRODUCTS;

2. SELECT * FROM CUSTOMERS AS CLIENTS;

3. SELECT PRODUCTNAME FROM PRODUCTS
   UNION
   SELECT PRODUCTNAME FROM PRODUCTS_DISCOUNTED;  

4. SELECT PRODUCTNAME FROM PRODUCTS
   INTERSECT
   SELECT PRODUCTNAME FROM PRODUCTS_DISCOUNTED;

5. SELECT DISTINCT FIRSTNAME, COUNTRY FROM CUSTOMERS;

6.SELECT PRODUCTNAME, PRICE,
  CASE 
    WHEN PRICE > 1000 THEN 'HIGH'
    WHEN PRICE <= 1000 THEN 'LOW'
    END AS PRICE_COMMENT
   FROM PRODUCTS;

7. SELECT 
      PRODUCTID, 
      PRODUCTNAME, 
      STOCKQUANTITY,
      IIF(STOCKQUANTITY > 100, 'YES', 'NO')
   AS STOCK_STATUS
   FROM Products_Discounted;

8. SELECT PRODUCTNAME FROM PRODUCTS
   UNION
   SELECT PRODUCTNAME FROM PRODUCTS_DISCOUNTED;  

9. SELECT ProductName
   FROM Products
   EXCEPT
   SELECT ProductName
   FROM Products_Discounted;

10. SELECT PRODUCTNAME,  
           PRICE,
           IIF(PRICE > 1000, 'EXPENSIVE', 'AFFORDABLE')
    AS PRICE_CATEGORY
    FROM PRODUCTS;

11. SELECT *
    FROM Employees
    WHERE Age < 25 OR Salary > 60000;

12. UPDATE EMPLOYEES
    SET SALARY = SALARY * 1.10
    WHERE DEPARTMENTNAME = 'HR';

13. SELECT SALEID, SALEAMOUNT,
   CASE 
    WHEN SALEAMOUNT > 500 THEN 'TOP TIER'
    WHEN SALEAMOUNT BETWEEN 200 AND 500 THEN 'MID TIER'
    ELSE 'LOW TIER'
    END AS SALES_CATEGORY
    FROM SALES;

14. SELECT CUSTOMERID FROM ORDERS
    EXCEPT
    SELECT CUSTOMERID FROM SALES;

15. SELECT CUSTOMERID, QUANTITY,
    CASE 
      WHEN QUANTITY = 1 THEN '3%'
      WHEN QUANTITY BETWEEN 1 AND 3 THEN '5%'
    ELSE '7%'
    END AS DISCOUNT_PERCENTAGE
    FROM ORDERS;
